CREATE TABLE [app].[pipeline_control] (

	[control_id] bigint IDENTITY NOT NULL, 
	[pipeline_name] varchar(200) NOT NULL, 
	[source_system] varchar(100) NOT NULL, 
	[source_entity] varchar(200) NOT NULL, 
	[source_connection_string] varchar(500) NULL, 
	[key_vault_url] varchar(500) NULL, 
	[target_schema] varchar(50) NOT NULL, 
	[target_table] varchar(200) NOT NULL, 
	[source_query_template] varchar(max) NULL, 
	[from_date] datetime2(6) NULL, 
	[to_date] datetime2(6) NULL, 
	[watermark_column] varchar(200) NULL, 
	[last_watermark] varchar(500) NULL, 
	[load_type] varchar(20) NOT NULL, 
	[is_active] bit NOT NULL, 
	[load_frequency] varchar(50) NULL, 
	[priority] int NOT NULL, 
	[dependency_on] varchar(200) NULL, 
	[last_run_status] varchar(20) NULL, 
	[last_run_date] datetime2(6) NULL, 
	[version_number] int NOT NULL, 
	[row_hash] varchar(64) NULL, 
	[created_date] datetime2(6) NOT NULL, 
	[created_by] varchar(200) NOT NULL, 
	[modified_date] datetime2(6) NOT NULL, 
	[modified_by] varchar(200) NOT NULL, 
	[primary_key] varchar(200) NULL
);