name: 'Create/Update Infrastructure (Automatic)'

on:
  push:
    branches: [ "main", "staging" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: "Terraform Formatting Check"
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./terraform

  # scan:
  #   name: "Security Scan (Terrascan)"
  #   runs-on: self-hosted
  #   defaults:
  #     run:
  #       shell: bash
  #   needs: lint
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Terrascan Install
  #       run: |
  #         curl --location https://github.com/accurics/terrascan/releases/download/v1.3.1/terrascan_1.3.1_Linux_x86_64.tar.gz --output terrascan.tar.gz
  #         tar -xvf terrascan.tar.gz
  #         sudo install terrascan /usr/local/bin

  #     - name: Run Terrascan
  #       run: terrascan scan -t azure -i terraform --skip-rules="accurics.azure.NS.272"
  #       working-directory: terraform

  plan:
    name: "Terraform Plan"
    runs-on: self-hosted
    needs: [lint]
    environment: test
    # needs: [lint, scan]
    defaults:
      run:
        shell: bash
    env:
      ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ vars.TF_VAR_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.TF_VAR_TENANT_ID }}

      TF_VAR_LICENSEPLATE: ${{ vars.TF_VAR_LICENSEPLATE }}
      TF_VAR_LOCATION: ${{ vars.TF_VAR_LOCATION }}
      TF_VAR_LOCATIONABBR: ${{ vars.TF_VAR_LOCATIONABBR }}
      TF_VAR_subnet_names: ${{ vars.TF_VAR_SUBNET_NAMES }}
      TF_VAR_tenant_id: ${{ vars.TF_VAR_TENANT_ID }}
      TF_VAR_TAGS: ${{ vars.TF_VAR_TAGS }}
      TF_VAR_JUMPBOX_SKU: ${{ vars.TF_VAR_JUMPBOX_SKU }}
      TF_VAR_environment: ${{ vars.TF_VAR_ENVIRONMENT }}
      TF_VAR_subscription_id: ${{ vars.TF_VAR_SUBSCRIPTION_ID }}
      TF_VAR_address_space: ${{ secrets.ADDRESS_SPACE }}
      TF_VAR_virtual_network_name: ${{ vars.virtual_network_name }}
      TF_VAR_virtual_network_resource_group: ${{ vars.virtual_network_resource_group }}
      TF_VAR_bastionSubnetAddressPrefix: ${{ vars.bastionSubnetAddressPrefix }}

      service_principal_id: ${{ secrets.service_principal_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0

      - name: Azure Login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          tenant-id: ${{ vars.TF_VAR_TENANT_ID }}
          subscription-id: ${{ vars.TF_VAR_SUBSCRIPTION_ID }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Shell Script - Create/Update Backend
        env:
          ENVIRONMENT: ${{ vars.TF_VAR_ENVIRONMENT }}
          RESOURCE_GROUP_NAME: ${{ vars.UNMANAGED_RG }}
          STORAGE_ACCOUNT_NAME: ${{ vars.UNMANAGED_STORAGE_TFSTATE }}
          CONTAINER_NAME: tfstate
          SUBSCRIPTION_ID: ${{ vars.TF_VAR_SUBSCRIPTION_ID }}
        run: |
          pwd
          node --version
          #echo ${{ github.event.inputs.environment }}
          chmod +x createbackend.sh
          #./createbackend.sh ${{ github.event.inputs.environment }}
          ./createbackend.sh test
        working-directory: scripts

      - name: Terraform Init
        #run: terraform init -upgrade -backend-config="environments/${{ github.event.inputs.environment }}/backend.conf"
        run: terraform init -upgrade -backend-config="../environments/test/backend.conf"
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -input=false -out=tf.plan
        working-directory: ./terraform

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./terraform/tf.plan
          retention-days: 1

  apply:
    name: "Terraform Apply"
    runs-on: self-hosted
    needs: plan
    environment: test
    if: >
      needs.plan.result == 'success' &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging') &&
      github.event_name == 'push'
    defaults:
      run:
        shell: bash
    env:
      ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ vars.TF_VAR_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.TF_VAR_TENANT_ID }}

      TF_VAR_LICENSEPLATE: ${{ vars.TF_VAR_LICENSEPLATE }}
      TF_VAR_LOCATION: ${{ vars.TF_VAR_LOCATION }}
      TF_VAR_LOCATIONABBR: ${{ vars.TF_VAR_LOCATIONABBR }}
      TF_VAR_subnet_names: ${{ vars.TF_VAR_SUBNET_NAMES }}
      TF_VAR_tenant_id: ${{ vars.TF_VAR_TENANT_ID }}
      TF_VAR_TAGS: ${{ vars.TF_VAR_TAGS }}
      TF_VAR_JUMPBOX_SKU: ${{ vars.TF_VAR_JUMPBOX_SKU }}
      TF_VAR_environment: ${{ vars.TF_VAR_ENVIRONMENT }}
      TF_VAR_subscription_id: ${{ vars.TF_VAR_SUBSCRIPTION_ID }}
      TF_VAR_address_space: ${{ secrets.ADDRESS_SPACE }}
      TF_VAR_virtual_network_name: ${{ vars.virtual_network_name }}
      TF_VAR_virtual_network_resource_group: ${{ vars.virtual_network_resource_group }}
      TF_VAR_bastionSubnetAddressPrefix: ${{ vars.bastionSubnetAddressPrefix }}

      service_principal_id: ${{ secrets.service_principal_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          tenant-id: ${{ vars.TF_VAR_TENANT_ID }}
          subscription-id: ${{ vars.TF_VAR_SUBSCRIPTION_ID }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download Plan Artifacts
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false tf.plan
        working-directory: ./terraform
        