name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write  # Required if Terraform needs to update state files or perform actions

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Terraform Init
      run: terraform init -backend-config="environments/test/backend.conf"
      working-directory: ./terraform

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan \
          -input=false \
          -var="ADDRESS_SPACE=${{ secrets.ADDRESS_SPACE }}" \
          -var="SERVICE_PRINCIPAL_ID=${{ secrets.SERVICE_PRINCIPAL_ID }}"
      working-directory: ./terraform

    # # Uncomment and adjust conditions for apply if needed
    # - name: Terraform Apply
    #   if: success() && github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: terraform apply -auto-approve -input=false
    #   working-directory: ./terraform
