name: 'Destroy Infrastructure'

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  InfrastructureDestroy:
    name: 'Deployment'
    runs-on: ["self-hosted"]
    environment: test

    defaults:
      run:
        shell: bash

    steps:

    - name: Runner Information
      run: echo "Runner Information ${{ runner }}, initiated by  - ${{ github.actor }}"

    - name: Checkout
      uses: actions/checkout@v4

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v3.0.0

    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        client-id: ${{ secrets.SERVICE_PRINCIPAL_ID }}
        tenant-id: ${{ vars.TF_VAR_TENANT_ID }}
        subscription-id: ${{ vars.TF_VAR_SUBSCRIPTION_ID }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set Azure Service Principal Environment Variables
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.SERVICE_PRINCIPAL_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ vars.TF_VAR_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ vars.TF_VAR_TENANT_ID }}" >> $GITHUB_ENV

    - name: Shell Script - Create/Update Backend
      env: 
        ENVIRONMENT: ${{ vars.TF_VAR_ENVIRONMENT }}
        RESOURCE_GROUP_NAME: ${{ vars.UNMANAGED_RG }}
        STORAGE_ACCOUNT_NAME: ${{ vars.UNMANAGED_STORAGE_TFSTATE }}
        CONTAINER_NAME: tfstate
        SUBSCRIPTION_ID: ${{ vars.TF_VAR_SUBSCRIPTION_ID }}
        
      run: |
        pwd
        node --version
        chmod +x createbackend.sh
        ./createbackend.sh test
      working-directory: scripts
        
    - name: Terraform Init
      run: terraform init -backend-config="../environments/test/backend.conf"
      working-directory: ./terraform

    - name: Terraform Destroy
      env:
        TF_VAR_LICENSEPLATE: ${{ vars.TF_VAR_LICENSEPLATE }}
        TF_VAR_LOCATION: ${{ vars.TF_VAR_LOCATION }}
        TF_VAR_LOCATIONABBR: ${{ vars.TF_VAR_LOCATIONABBR }}
        TF_VAR_subnet_names: ${{ vars.TF_VAR_SUBNET_NAMES }}
        TF_VAR_tenant_id: ${{ vars.TF_VAR_TENANT_ID }}
        TF_VAR_TAGS: ${{ vars.TF_VAR_TAGS }}
        TF_VAR_JUMPBOX_SKU: ${{ vars.TF_VAR_JUMPBOX_SKU }}
        TF_VAR_environment: ${{ vars.TF_VAR_ENVIRONMENT }}
        service_principal_id: ${{ secrets.service_principal_id }}
        TF_VAR_subscription_id: ${{ vars.TF_VAR_SUBSCRIPTION_ID }}
        TF_VAR_address_space: ${{ secrets.ADDRESS_SPACE }}
        TF_VAR_virtual_network_name: ${{ vars.virtual_network_name }}
        TF_VAR_virtual_network_resource_group: ${{ vars.virtual_network_resource_group }}
        TF_VAR_bastionSubnetAddressPrefix: ${{ vars.bastionSubnetAddressPrefix }}
      run: terraform destroy -auto-approve -input=false
      working-directory: ./terraform